;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	xah-comment-dwim
	xah-fly-command-mode-activate
	xah-fly-insert-mode-activate
	))

(setq mc/cmds-to-run-once
      '(
	))
